#!/bin/bash

# ibrunton's herbstluftwm config
# 2012-05-06

function hc () {
	herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all
hc mouseunbind

# make room for dzen2 bar
hc pad 0 10 0 0

# variables
colour_normal='#666666' #'#ae8451'
colour_active='#426797' #'#f6ff00'
terminal=urxvt
emacs=emet
file_manager=dolphin
browser=firefox
alternate_browser=luakit

# keybindings
mod=Mod4

# programs & overall functions
hc keybind $mod-Control-Shift-r reload
hc keybind $mod-Shift-q quit
hc keybind $mod-Shift-c close
hc keybind $mod-Return spawn $terminal
hc keybind $mod-Shift-Return spawn $emacs
hc keybind $mod-Shift-Escape spawn $HOME/bin/slrh.sh
hc keybind $mod-p spawn dmenu_run -fn "-misc-ohsnap-medium-r-normal--11-79-100-100-c-60-iso8859-1" -nb '#000000' -nf '#e0e0e0' -sb '#000000' -sf '#4abcd4'
hc keybind $mod-Shift-p spawn $HOME/bin/dmenu_custom.bash
hc keybind $mod-w spawn $browser
hc keybind $mod-Shift-w spawn $alternate_browser
hc keybind $mod-m spawn $HOME/bin/mygtkmenu.py
hc keybind $mod-t spawn $file_manager
hc keybind $mod-b emit_hook togglehidepanel

# keybindings: tags
TAG_NAMES=( {1..6} )
TAG_KEYS=( {1..6} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
	hc add "${TAG_NAMES[$i]}"
	key="${TAG_KEYS[$i]}"
	if ! [-z "$key" ] ; then
		hc keybind "$mod-$key" use_index $((key - 1)) #use "${TAG_NAMES[$i]}"
		hc keybind "$mod-Shift-$key" move_index $((key - 1)) #move "${TAG_NAMES[$i]}"
	fi
done

# keybindings: layout
hc keybind $mod-Control-d remove
hc keybind $mod-a split horizontal 0.5
hc keybind $mod-s split horizontal 0.33
hc keybind $mod-z split vertical 0.5
hc keybind $mod-x split vertical 0.33
hc keybind $mod-space cycle_layout 1 && hc emit_hook layoutchanged
hc keybind $mod-Shift-space cycle_layout -1 && hc emit_hook layoutchanged
hc keybind $mod-Shift-m set_layout max
hc keybind $mod-Shift-t set_layout horizontal
hc keybind $mod-Shift-v set_layout vertical
hc keybind $mod-Shift-g set_layout grid
hc keybind $mod-Shift-f floating toggle

# keybindings: resizing
RESIZESTEP=0.05
hc keybind $mod-Control-h resize left +$RESIZESTEP
hc keybind $mod-Control-k resize up +$RESIZESTEP
hc keybind $mod-Control-j resize down +$RESIZESTEP
hc keybind $mod-Control-l resize right +$RESIZESTEP

# keybindings: focus
hc keybind $mod-Tab cycle_all +1
hc keybind $mod-Shift-Tab cycle_all -1
hc keybind $mod-c cycle
hc keybind $mod-h focus left
hc keybind $mod-j focus down
hc keybind $mod-k focus up
hc keybind $mod-l focus right
hc keybind $mod-Shift-h shift left
hc keybind $mod-Shift-j shift down
hc keybind $mod-Shift-k shift up
hc keybind $mod-Shift-l shift right

# keybindings: volume
hc keybind $mod-F10 spawn volosd.sh down -i 1
hc keybind $mod-F11 spawn volosd.sh mute
hc keybind $mod-F12 spawn volosd.sh up -i 1

# colours/appearance
hc set default_frame_layout 1
hc set frame_bg_transparent 1
hc set frame_border_width 0
hc set window_border_width 1
hc set window_border_normal_color $colour_normal
hc set window_border_active_color $colour_active
hc set window_gap 5
hc set snap_distance 15
hc set tree_style "╾│ ├└╼─┐"

# tiled tag layouts
#hc load ${TAG_NAMES[0]} "(split vertical:0.700000:0 (split horizontal:0.400000:1 (clients horizontal:0) (clients horizontal:0)) (split horizontal:0.500000:0 (clients horizontal:0) (clients horizontal:0)))"
hc load ${TAG_NAMES[0]} "(split horizontal:0.450000:1 (split vertical:0.500000:1 (clients horizontal:0) (clients horizontal:0 0x1a00007)) (split vertical:0.650000:0 (clients horizontal:0 0x1800007) (clients horizontal:0)))"
hc load ${TAG_NAMES[1]} "(split horizontal:0.750000:0 (clients horizontal:0) (clients horizontal:1))"
hc load ${TAG_NAMES[3]} "(split horizontal:0.550000:0 (clients vertical:0) (clients horizontal:0))"
hc load ${TAG_NAMES[4]} "(split horizontal:0.550000:0 (clients max:0) (clients horizontal:0))"

# floating tags
hc floating ${TAG_NAMES[2]} on
hc floating ${TAG_NAMES[5]} on
hc set raise_on_click 1
hc set raise_on_focus 1

# mouse buttons
hc mousebind $mod+Button1 move
hc mousebind $mod+Button3 resize

# rules
hc unrule -F
hc rule focus=on
hc rule class=Firefox tag=${TAG_NAMES[1]}
hc rule class=gimp tag=${TAG_NAMES[5]} pseudotile=on
hc rule class=Okular tag=${TAG_NAMES[4]}
hc rule class=URxvt instance=MAILTO pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_DIALOG' pseudotile=on
hc rule class=Kdialog pseudotile=on
hc rule class=sxiv pseudotile=on

# unlock
hc unlock

# panel
conky &
